"use client";

import { X, Cpu, Info } from "lucide-react";
import { useAppStore } from "@/lib/store";
import { explanations } from "@/lib/mock-data";

export default function ExplainModal() {
  const {
    explainOpen,
    explainNode,
    explainTitle,
    explainContent,
    closeExplain,
  } = useAppStore();

  if (!explainOpen || !explainNode) return null;

  const title =
    explainTitle ||
    explainNode.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());

  const content =
    explainContent ||
    explanations[explainNode] ||
    "Component generated by the AI Architecture Engine (REE + SAE).";

  const isJson = content.trim().startsWith("{") || content.trim().startsWith("[");

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
      <div className="relative mx-auto w-full max-w-xl rounded-2xl border border-gray-200 bg-white p-6 shadow-2xl dark:border-gray-800 dark:bg-gray-900">
        {/* Close */}
        <button
          onClick={closeExplain}
          className="absolute right-4 top-4 rounded-lg p-1.5 text-gray-400 transition-colors hover:bg-gray-100 dark:hover:bg-gray-800"
        >
          <X className="h-5 w-5" />
        </button>

        {/* Header */}
        <div className="mb-4 flex items-center gap-3">
          <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-indigo-500 to-purple-600 shadow-md shadow-indigo-500/25">
            <Cpu className="h-5 w-5 text-white" />
          </div>
          <div>
            <h3 className="text-base font-bold text-gray-900 dark:text-white">
              {title}
            </h3>
            <p className="text-xs text-gray-500">Component Specification & Explanation</p>
          </div>
        </div>

        {/* Body */}
        <div className="max-h-96 overflow-y-auto pr-1">
          {isJson ? (
            <pre className="rounded-xl border border-gray-200 bg-gray-50 p-4 font-mono text-xs text-gray-800 dark:border-gray-800 dark:bg-gray-950 dark:text-gray-200">
              {content}
            </pre>
          ) : (
            <p className="leading-relaxed text-sm text-gray-700 dark:text-gray-300">
              {content}
            </p>
          )}
        </div>

        {/* Footer */}
        <div className="mt-6 flex justify-end">
          <button
            onClick={closeExplain}
            className="rounded-xl bg-gradient-to-r from-indigo-500 to-purple-600 px-5 py-2 text-xs font-semibold text-white shadow-md shadow-indigo-500/20 transition-opacity hover:opacity-90"
          >
            Got it
          </button>
        </div>
      </div>
    </div>
  );
}
