"use client";

import { useState } from "react";
import {
  Network,
  Copy,
  Check,
  ArrowLeft,
  ArrowRight,
  Info,
} from "lucide-react";
import { useAppStore } from "@/lib/store";
import HLDGraph from "./HLDGraph";

export default function HldView() {
  const { hldData, setActivePipelineStep, openExplain } = useAppStore();
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    if (!hldData) return;
    navigator.clipboard.writeText(JSON.stringify(hldData, null, 2));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="flex h-full flex-col bg-white text-black dark:bg-black dark:text-white transition-colors">
      {/* Top action header */}
      <div className="flex items-center justify-between border-b border-neutral-200 bg-white px-6 py-3.5 dark:border-neutral-800 dark:bg-black">
        <div className="flex items-center gap-2.5">
          <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-black text-white dark:bg-white dark:text-black shadow-xs">
            <Network className="h-4 w-4" />
          </div>
          <div>
            <h2 className="font-heading text-sm font-bold tracking-tight text-black dark:text-white">
              High-Level Design (HLD) Architecture
            </h2>
            <p className="text-[11px] text-neutral-500 dark:text-neutral-400">
              Interactive system topology diagram dynamically generated by the SAE engine
            </p>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 rounded-lg border border-neutral-300 bg-white px-3 py-1.5 text-xs font-semibold text-neutral-800 shadow-xs transition-all hover:border-black hover:text-black dark:border-neutral-700 dark:bg-neutral-900 dark:text-neutral-300 dark:hover:border-white dark:hover:text-white"
          >
            {copied ? (
              <Check className="h-3.5 w-3.5 text-black dark:text-white" />
            ) : (
              <Copy className="h-3.5 w-3.5" />
            )}
            <span>{copied ? "Copied" : "Copy JSON"}</span>
          </button>

          <button
            onClick={() =>
              openExplain(
                "hld-overview",
                "High-Level Design Architecture",
                hldData
                  ? JSON.stringify(hldData, null, 2)
                  : "High-Level Design diagram generated by the SAE engine."
              )
            }
            className="flex items-center gap-1 rounded-lg border border-neutral-300 bg-white px-3 py-1.5 text-xs font-semibold text-neutral-800 shadow-xs hover:border-black hover:text-black dark:border-neutral-700 dark:bg-neutral-900 dark:text-neutral-300 dark:hover:border-white dark:hover:text-white"
          >
            <Info className="h-3.5 w-3.5" />
            <span>Details</span>
          </button>

          <button
            onClick={() => setActivePipelineStep(4)}
            className="flex items-center gap-1.5 rounded-lg bg-black px-4 py-1.5 text-xs font-semibold text-white transition-all hover:bg-neutral-800 dark:bg-white dark:text-black dark:hover:bg-neutral-200"
          >
            <span>Explore 5 LLDs</span>
            <ArrowRight className="h-3.5 w-3.5" />
          </button>
        </div>
      </div>

      {/* Main Visual Diagram Canvas */}
      <div className="relative flex-1 bg-neutral-50 dark:bg-black">
        <div className="absolute left-4 top-4 z-10 flex items-center gap-2 rounded-lg border border-neutral-300 bg-white/95 px-3.5 py-1.5 text-xs font-medium text-black shadow-xs backdrop-blur-md dark:border-neutral-700 dark:bg-neutral-900/95 dark:text-white">
          <span className="h-2 w-2 rounded-full bg-black dark:bg-white" />
          <span>Click any component node to inspect details and jump to its LLD</span>
        </div>

        <HLDGraph />
      </div>

      {/* Bottom Slider Footer */}
      <div className="flex items-center justify-between border-t border-neutral-200 bg-white px-6 py-3 dark:border-neutral-800 dark:bg-black">
        <button
          onClick={() => setActivePipelineStep(2)}
          className="flex items-center gap-1.5 rounded-lg border border-neutral-300 bg-white px-4 py-2 text-xs font-semibold text-neutral-700 transition-colors hover:border-black hover:text-black dark:border-neutral-700 dark:bg-neutral-900 dark:text-neutral-300 dark:hover:border-white dark:hover:text-white"
        >
          <ArrowLeft className="h-3.5 w-3.5" />
          <span>Back to ARSRS Document</span>
        </button>

        <button
          onClick={() => setActivePipelineStep(4)}
          className="flex items-center gap-1.5 rounded-lg bg-black px-5 py-2 text-xs font-semibold text-white transition-all hover:bg-neutral-800 dark:bg-white dark:text-black dark:hover:bg-neutral-200"
        >
          <span>Explore Low-Level Designs (5 LLDs)</span>
          <ArrowRight className="h-3.5 w-3.5" />
        </button>
      </div>
    </div>
  );
}
