"use client";

import { useState } from "react";
import {
  Network,
  Copy,
  Check,
  ArrowLeft,
  ArrowRight,
  Info,
} from "lucide-react";
import { useAppStore } from "@/lib/store";
import HLDGraph from "./HLDGraph";

export default function HldView() {
  const { hldData, setActivePipelineStep, openExplain } = useAppStore();
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    if (!hldData) return;
    navigator.clipboard.writeText(JSON.stringify(hldData, null, 2));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="flex h-full flex-col bg-white dark:bg-black">
      {/* Top action header */}
      <div className="flex items-center justify-between border-b border-gray-200 bg-white/80 px-6 py-3.5 backdrop-blur-md dark:border-gray-800 dark:bg-black/80">
        <div className="flex items-center gap-2">
          <div className="flex h-8 w-8 items-center justify-center rounded-xl bg-gradient-to-br from-indigo-500 to-purple-600 text-white shadow-sm">
            <Network className="h-4 w-4" />
          </div>
          <div>
            <h2 className="text-sm font-bold text-gray-900 dark:text-white">
              High-Level Design (HLD) Visualization
            </h2>
            <p className="text-[11px] text-gray-500">
              Interactive system architecture diagram dynamically generated from backend SAE engine
            </p>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 rounded-xl border border-gray-200 bg-white px-3 py-1.5 text-xs font-semibold text-gray-700 shadow-sm transition-all hover:bg-gray-50 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-200 dark:hover:bg-gray-800"
          >
            {copied ? (
              <Check className="h-3.5 w-3.5 text-emerald-500" />
            ) : (
              <Copy className="h-3.5 w-3.5" />
            )}
            <span>{copied ? "Copied" : "Copy JSON"}</span>
          </button>

          <button
            onClick={() =>
              openExplain(
                "hld-overview",
                "High-Level Design Architecture",
                hldData
                  ? JSON.stringify(hldData, null, 2)
                  : "High-Level Design diagram generated by the SAE engine."
              )
            }
            className="flex items-center gap-1 rounded-xl border border-gray-200 bg-white px-3 py-1.5 text-xs font-semibold text-gray-700 shadow-sm hover:bg-gray-50 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-200"
          >
            <Info className="h-3.5 w-3.5" />
            <span>Details</span>
          </button>

          <button
            onClick={() => setActivePipelineStep(4)}
            className="flex items-center gap-1.5 rounded-xl bg-gradient-to-r from-indigo-500 to-purple-600 px-4 py-1.5 text-xs font-semibold text-white shadow-md shadow-indigo-500/20 transition-all hover:opacity-95"
          >
            <span>Explore 5 LLDs</span>
            <ArrowRight className="h-3.5 w-3.5" />
          </button>
        </div>
      </div>

      {/* Main Visual Diagram Canvas */}
      <div className="relative flex-1 bg-white dark:bg-black">
        <div className="absolute left-4 top-4 z-10 rounded-xl border border-gray-200 bg-white/90 px-3 py-1.5 text-xs font-medium text-gray-600 shadow-sm backdrop-blur-md dark:border-gray-800 dark:bg-gray-900/90 dark:text-gray-300">
          💡 Click any component node to inspect details and jump to its LLD
        </div>

        <HLDGraph />
      </div>

      {/* Bottom Slider Footer */}
      <div className="flex items-center justify-between border-t border-gray-200 bg-white/80 px-6 py-3 backdrop-blur-md dark:border-gray-800 dark:bg-black/80">
        <button
          onClick={() => setActivePipelineStep(2)}
          className="flex items-center gap-1.5 rounded-xl border border-gray-200 bg-white px-4 py-2 text-xs font-semibold text-gray-700 transition-colors hover:bg-gray-50 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-200 dark:hover:bg-gray-800"
        >
          <ArrowLeft className="h-3.5 w-3.5" />
          <span>Back to ARSRS Document</span>
        </button>

        <button
          onClick={() => setActivePipelineStep(4)}
          className="flex items-center gap-1.5 rounded-xl bg-gradient-to-r from-indigo-500 to-purple-600 px-5 py-2 text-xs font-semibold text-white shadow-md shadow-indigo-500/20 transition-all hover:opacity-95"
        >
          <span>Explore Low-Level Designs (5 LLDs)</span>
          <ArrowRight className="h-3.5 w-3.5" />
        </button>
      </div>
    </div>
  );
}
