"use client";

import React, { useState } from "react";
import {
  Network,
  Copy,
  Check,
  Info,
  Maximize2,
  Sparkles,
} from "lucide-react";
import { useAppStore } from "@/lib/store";
import HLDGraph from "./HLDGraph";

export default function HldWorkspace() {
  const { hldData, openExplain, hldNodes } = useAppStore();
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    if (!hldData) return;
    navigator.clipboard.writeText(JSON.stringify(hldData, null, 2));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="flex h-full w-full flex-col overflow-hidden bg-white text-black dark:bg-black dark:text-white transition-colors">
      {/* Top action toolbar */}
      <div className="flex items-center justify-between border-b border-neutral-200 bg-white/95 px-5 py-3 dark:border-neutral-800/90 dark:bg-neutral-950/95 backdrop-blur-md shrink-0">
        <div className="flex items-center gap-2.5">
          <div className="flex h-8 w-8 items-center justify-center rounded-xl bg-black text-white dark:bg-white dark:text-black shadow-xs">
            <Network className="h-4 w-4" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-sm font-bold tracking-tight text-neutral-900 dark:text-white">
                High-Level Design (HLD) Architecture
              </h2>
              <span className="rounded-md bg-blue-500/10 border border-blue-500/20 px-2 py-0.5 text-[10px] font-semibold text-blue-600 dark:text-blue-400">
                {hldNodes.length} Components
              </span>
            </div>
            <p className="text-[11px] text-neutral-500 dark:text-neutral-400">
              Interactive system topology diagram generated by the SAE multi-agent engine
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handleCopy}
            className="flex items-center gap-1.5 rounded-xl border border-neutral-300 bg-white px-3 py-1.5 text-xs font-semibold text-neutral-800 shadow-xs transition-all hover:border-black hover:text-black dark:border-neutral-700 dark:bg-neutral-900 dark:text-neutral-300 dark:hover:border-white dark:hover:text-white cursor-pointer"
          >
            {copied ? (
              <Check className="h-3.5 w-3.5 text-emerald-500" />
            ) : (
              <Copy className="h-3.5 w-3.5" />
            )}
            <span>{copied ? "Copied" : "Copy JSON"}</span>
          </button>

          <button
            type="button"
            onClick={() =>
              openExplain(
                "hld-overview",
                "High-Level Design Architecture Specification",
                hldData
                  ? JSON.stringify(hldData, null, 2)
                  : "High-Level Design diagram generated by the SAE multi-agent engine."
              )
            }
            className="flex items-center gap-1.5 rounded-xl border border-neutral-300 bg-white px-3 py-1.5 text-xs font-semibold text-neutral-800 shadow-xs hover:border-black hover:text-black dark:border-neutral-700 dark:bg-neutral-900 dark:text-neutral-300 dark:hover:border-white dark:hover:text-white cursor-pointer"
          >
            <Info className="h-3.5 w-3.5" />
            <span>Specifications</span>
          </button>
        </div>
      </div>

      {/* Main Diagram Canvas */}
      <div className="relative flex-1 bg-neutral-50 dark:bg-black min-h-0">
        <HLDGraph />
      </div>
    </div>
  );
}
