"""Deterministic OpenAPI 3.1.0 YAML Generator for SAE v2."""

from __future__ import annotations

import json
from typing import Any, Dict, List, Optional


def generate_openapi_spec(
    system_name: str,
    domain: str,
    backend_lld: Dict[str, Any],
    security_lld: Optional[Dict[str, Any]] = None,
) -> str:
    """Generate clean, valid OpenAPI 3.1.0 YAML from backend and security LLD specifications."""
    endpoints: List[Dict[str, Any]] = backend_lld.get("api_endpoints", [])
    framework = backend_lld.get("framework_config", {}).get("framework", "FastAPI (Python)")

    lines: List[str] = [
        "openapi: 3.1.0",
        "info:",
        f'  title: "{system_name} API"',
        f'  description: "Production API specification for {system_name} ({domain}). Generated by SAE v2 Engine."',
        '  version: "1.0.0"',
        "servers:",
        '  - url: "http://localhost:8000"',
        '    description: "Local Development Server"',
        '  - url: "https://api.staging.internal"',
        '    description: "Staging Cluster Environment"',
        "paths:",
    ]

    if not endpoints:
        # Fallback health check if endpoints list was empty
        lines.extend([
            "  /health:",
            "    get:",
            '      summary: "System Health Probe"',
            "      responses:",
            "        '200':",
            '          description: "Service is healthy"',
        ])
    else:
        # Group endpoints by route path
        by_route: Dict[str, List[Dict[str, Any]]] = {}
        for ep in endpoints:
            route = ep.get("route", "/api/v1/resource")
            by_route.setdefault(route, []).append(ep)

        for route, methods_list in by_route.items():
            lines.append(f"  {route}:")
            for ep in methods_list:
                method = str(ep.get("method", "GET")).lower()
                desc = ep.get("description", "API Operation")
                auth_req = ep.get("auth_required", False)
                req_info = ep.get("request", {})
                resp_info = ep.get("response", {})
                error_resps = ep.get("error_responses", [])

                lines.append(f"    {method}:")
                lines.append(f'      summary: "{desc}"')
                lines.append(f'      description: "{desc} — Concurrency: {ep.get("concurrency_note", "Standard")}"')

                if auth_req:
                    lines.append("      security:")
                    lines.append("        - BearerAuth: []")

                # Path & Query parameters
                params_lines: List[str] = []
                for p in req_info.get("path_params", []):
                    params_lines.append(f"        - name: {p}")
                    params_lines.append("          in: path")
                    params_lines.append("          required: true")
                    params_lines.append("          schema:")
                    params_lines.append("            type: string")

                for q in req_info.get("query_params", []):
                    params_lines.append(f"        - name: {q}")
                    params_lines.append("          in: query")
                    params_lines.append("          required: false")
                    params_lines.append("          schema:")
                    params_lines.append("            type: string")

                if params_lines:
                    lines.append("      parameters:")
                    lines.extend(params_lines)

                # Request Body
                if "body" in req_info and method in ["post", "put", "patch"]:
                    lines.append("      requestBody:")
                    lines.append("        required: true")
                    lines.append("        content:")
                    lines.append("          application/json:")
                    lines.append("            schema:")
                    lines.append("              type: object")
                    body_data = req_info["body"]
                    if isinstance(body_data, dict):
                        lines.append("              properties:")
                        for prop, ptype in body_data.items():
                            js_type = "integer" if "int" in str(ptype).lower() else ("boolean" if "bool" in str(ptype).lower() else "string")
                            lines.append(f"                {prop}:")
                            lines.append(f"                  type: {js_type}")
                    else:
                        lines.append("              additionalProperties: true")

                # Responses
                lines.append("      responses:")
                status_code = str(resp_info.get("status", 200))
                resp_body_desc = str(resp_info.get("body", "Successful operation"))
                lines.append(f"        '{status_code}':")
                lines.append(f'          description: "{resp_body_desc}"')
                lines.append("          content:")
                lines.append("            application/json:")
                lines.append("              schema:")
                lines.append("                type: object")

                # Error responses
                for err in error_resps:
                    if isinstance(err, dict):
                        err_status = str(err.get("status", 400))
                        err_code = err.get("code", "ERROR")
                        err_desc = err.get("description", "Error response")
                        lines.append(f"        '{err_status}':")
                        lines.append(f'          description: "[{err_code}] {err_desc}"')
                        lines.append("          content:")
                        lines.append("            application/problem+json:")
                        lines.append("              schema:")
                        lines.append("                $ref: '#/components/schemas/ProblemDetails'")

    # Components & Security Schemes
    lines.extend([
        "components:",
        "  securitySchemes:",
        "    BearerAuth:",
        "      type: http",
        "      scheme: bearer",
        "      bearerFormat: JWT",
        '      description: "OAuth2 JWT Bearer Token in Authorization header"',
        "  schemas:",
        "    ProblemDetails:",
        "      type: object",
        "      properties:",
        "        type:",
        "          type: string",
        "        title:",
        "          type: string",
        "        status:",
        "          type: integer",
        "        detail:",
        "          type: string",
        "        instance:",
        "          type: string",
        "        error_code:",
        "          type: string",
        "        timestamp:",
        "          type: string",
        "          format: date-time",
    ])

    return "\n".join(lines) + "\n"
