"""SAE v2 Lean Prompts Package."""

from .backend_lld_generation_prompt import (
    BACKEND_LLD_GENERATION_SYSTEM_PROMPT,
    BACKEND_LLD_GENERATION_USER_PROMPT_TEMPLATE,
)
from .cloud_lld_generation_prompt import (
    CLOUD_LLD_GENERATION_SYSTEM_PROMPT,
    CLOUD_LLD_GENERATION_USER_PROMPT_TEMPLATE,
)
from .database_lld_generation_prompt import (
    DATABASE_LLD_GENERATION_SYSTEM_PROMPT,
    DATABASE_LLD_GENERATION_USER_PROMPT_TEMPLATE,
)
from .frontend_lld_generation_prompt import (
    FRONTEND_LLD_GENERATION_SYSTEM_PROMPT,
    FRONTEND_LLD_GENERATION_USER_PROMPT_TEMPLATE,
)
from .hld_generation_prompt import (
    HLD_GENERATION_SYSTEM_PROMPT,
    HLD_GENERATION_USER_PROMPT_TEMPLATE,
)
from .requirement_analysis_prompt import (
    REQUIREMENT_ANALYSIS_SYSTEM_PROMPT,
    REQUIREMENT_ANALYSIS_USER_PROMPT_TEMPLATE,
)
from .security_lld_generation_prompt import (
    SECURITY_LLD_GENERATION_SYSTEM_PROMPT,
    SECURITY_LLD_GENERATION_USER_PROMPT_TEMPLATE,
)
from .technology_advisor_prompt import (
    TECHNOLOGY_ADVISOR_SYSTEM_PROMPT,
    TECHNOLOGY_ADVISOR_USER_PROMPT_TEMPLATE,
)

__all__ = [
    "REQUIREMENT_ANALYSIS_SYSTEM_PROMPT",
    "REQUIREMENT_ANALYSIS_USER_PROMPT_TEMPLATE",
    "TECHNOLOGY_ADVISOR_SYSTEM_PROMPT",
    "TECHNOLOGY_ADVISOR_USER_PROMPT_TEMPLATE",
    "HLD_GENERATION_SYSTEM_PROMPT",
    "HLD_GENERATION_USER_PROMPT_TEMPLATE",
    "BACKEND_LLD_GENERATION_SYSTEM_PROMPT",
    "BACKEND_LLD_GENERATION_USER_PROMPT_TEMPLATE",
    "DATABASE_LLD_GENERATION_SYSTEM_PROMPT",
    "DATABASE_LLD_GENERATION_USER_PROMPT_TEMPLATE",
    "FRONTEND_LLD_GENERATION_SYSTEM_PROMPT",
    "FRONTEND_LLD_GENERATION_USER_PROMPT_TEMPLATE",
    "SECURITY_LLD_GENERATION_SYSTEM_PROMPT",
    "SECURITY_LLD_GENERATION_USER_PROMPT_TEMPLATE",
    "CLOUD_LLD_GENERATION_SYSTEM_PROMPT",
    "CLOUD_LLD_GENERATION_USER_PROMPT_TEMPLATE",
]
