from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from app.services.elicitation.answer_merger import merge_answers
from app.services.elicitation.pipeline import run_elicitation_pipeline

router = APIRouter()


# ── Step 3 ──────────────────────────────────────────────────────────────────
# POST /api/elicit
# Input : extracted parameters + original prompt
# Output: missing parameter names + LLM-generated clarification questions

class ElicitationRequest(BaseModel):
    parameters: dict
    prompt: str


@router.post("/api/elicit")
def elicit_requirements(body: ElicitationRequest):
    """
    Step 3 — Detect missing parameters and generate clarification questions.

    Flow: /api/input → /api/extract → /api/elicit → /api/elicit/answer
    """
    if not body.prompt.strip():
        raise HTTPException(status_code=400, detail="prompt is empty.")
    if not body.parameters:
        raise HTTPException(status_code=400, detail="parameters is empty.")

    try:
        result = run_elicitation_pipeline(body.parameters, body.prompt)
        return result
    except RuntimeError as exc:
        raise HTTPException(status_code=502, detail=str(exc))


# ── Step 4 ──────────────────────────────────────────────────────────────────
# POST /api/elicit/answer
# Input : existing parameters + user answers to the elicitation questions
# Output: fully structured parameters (all missing values filled in)

class AnswerItem(BaseModel):
    parameter: str
    answer: str


class AnswerRequest(BaseModel):
    parameters: dict
    answers: list[AnswerItem]


@router.post("/api/elicit/answer")
def submit_answers(body: AnswerRequest):
    """
    Step 4 — Merge user answers into the parameter set.

    Accepts the parameters dict from /api/extract and the user's answers
    to the questions generated by /api/elicit.  Returns a fully populated
    parameters dict with no null values.

    Flow: /api/input → /api/extract → /api/elicit → /api/elicit/answer
    """
    if not body.answers:
        raise HTTPException(status_code=400, detail="answers list is empty.")
    if not body.parameters:
        raise HTTPException(status_code=400, detail="parameters is empty.")

    answers_raw = [{"parameter": a.parameter, "answer": a.answer} for a in body.answers]
    structured = merge_answers(body.parameters, answers_raw)
    return {"parameters": structured}
